version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AUTH_SERVICE_URL=http://auth-service:5000
      - REACT_APP_PROFILE_SERVICE_URL=http://profile-service:5001
    depends_on:
      - auth-service
      - profile-service
  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
  profile-service:
    build:
      context: ./profile_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
